### PR TITLE
fix

### PR DESCRIPTION
**Pull request by grant2258**
fix an issue z80 detection that  was was discussed on a 2003-plus issue.

### CODE REVIEW

**Comment by grant2258** [comment]
that should be you your run loop needed split a little to over ride the cpu

**Comment by KMFDManic** [comment]
Looks great, thank you!

**Comment by grant2258** [comment]
Sorry about that makes it a little harder when im not testing the code. It should be correct as it is in plus.

**Comment by KMFDManic** [comment]
@grant2258 no need to apologize.  I greatly appreciate all you do to help the Xtreme cause. Plus/Xtreme get better by the day with you and the others onboard:) I will get some videos up over the next few days, for sure!

**Comment by KMFDManic** [comment]
@grant2258 cyclone working great:) All else great.  I will respond in 2003 plus feed with some interesting test results, as well.

**Pull request merged**
