### PR TITLE
bootstraps

### PR DESCRIPTION
**Pull request by ghost**
yeap he has been busy fixing stuff up here is the stuff you wanted

You can add any games from plus like its done here

GAMEC( 1994, crusnusa, 0,        midvunit, crusnusa, crusnusa, ROT0, "Midway", "Cruis'n USA (rev L4.1)", NULL, &crusnusa_bootstrap )
GAMEC( 1994, crusnu40, crusnusa, midvunit, crusnusa, crusnu40, ROT0, "Midway", "Cruis'n USA (rev L4.0)", NULL, &crusnu40_bootstrap )
GAMEC( 1994, crusnu21, crusnusa, midvunit, crusnusa, crusnu21, ROT0, "Midway", "Cruis'n USA (rev L2.1)", NULL, &crusnu21_bootstrap )

I done Cruis'n USA for you. The second one from the end should always be NULL for you I done it this way so you can copy and paste.

Here is marks original documentation if you want to add any. All of pluses bootstraps are there already just need to update the GAME() declares in the drivers you want them active for. 

https://docs.libretro.com/development/cores/core-specific/mame-2003-plus/#purpose-and-criteria-for-bootstraps

### CODE REVIEW

**Comment by mahoneyt944** [comment]
Revx needs a few updates to fully work. You'll need to update dcs to active low then update all the drivers that use dcs_reset_w. Revx then gets this update in the machine driver. Here's the commit. https://github.com/libretro/mame2003-plus-libretro/commit/d890ff18863da33202c895d7cfbbc3ac655a544e

**Comment by ghost** [comment]
I havent done the midway updates on my core yet its a lot of testing to do.

**Comment by mahoneyt944** [comment]
I tested a lot of them when making the bootstraps. Most games don't seem to mind high or low being active, probably due to less accurate emulation of our code, when everything is set one way or the other that is. I decided to upgrade it though because a few games are picky about it and in future backports or game additions it may be required. I couldn't find any games that it didn't work with this change and it's been in plus and vanilla for awhile now.

In revx, what would happen is the volume, set all the way up in the service menu, would still not play loud at boot of the game unless you manually adjusted the volume after starting the game. Then after a full reset it would revert to quiet again. The dcs reset just initializes the volume in a nutshell.

We also control all sides of the coin because we decide which bit is active in "dcs" then configure each active bit in the driver, and finally set the which bit is used by "midwayic".

**Comment by KMFDManic** [comment]
@grant2258 @mahoneyt944 Thanks:)  The bootstrap implementation and execution really is a massive thing for MAME Emulation.  This is something that really should have been done ions ago, even in Standalone MAME!  MOST End Users would be perplexed about how to calibrate a game, and forbid they muck it up, and not know how to find and wipe the incorrect values, having broken games!  This will be fun adding this for myself and others.  Thanks, again:)

**Comment by ghost** [comment]
Mame current support nvram in the zip files when and if needed. Hopefully it all good. Plenty of time to test before your release.

**Comment by KMFDManic** [comment]
@grant2258 Hope all is well.  Have you ever played WWE All Stars on PS3?  Fun fun stuff.  I know you love your wrestling!  I am finally nearing the Next Release, after finishing up some N64 Stuff.  Thanks again for yours, @mahoneyt944 and @arcadez2003 help, as always!!!

**Comment by mahoneyt944** [comment]
I remember playing wwf smackdown: just bring it On ps2. You could make your own wrestler.

**Comment by ghost** [comment]
@KMFDManic I havent used my ps3 in a while havent played that particular game but the last thing I did for ps3 was put a new laser in and didnt use it! I loved heavenly sword its old but good! 

All is well here am really busy with work though and cant do anything else because of lockdown. I updated my mame roms gonna give gauntlet a spin with the new fixes for it. I also want try out the x6800 only tried a handful of games on that system but looks had some epic games by the looks of it for its time. I have no idea why amigas and st/ste sold more units than this system. Its the same for the turbo gfx was also an awesome system for its time that didnt make the spotlight outside of the oriental/Asian market.

**Comment by mahoneyt944** [comment]
@grant2258  Which new fixes for gauntlet?

**Comment by ghost** [comment]
Was protection stuff that got broke when they fixed an issue for another game

**Comment by mahoneyt944** [comment]
Which core

**Comment by ghost** [comment]
mame current 0228 using standalone  https://mametesters.org/view.php?id=7834

**Comment by KMFDManic** [comment]
@grant2258 @mahoneyt944 one of the coolest things about heavenly sword was the 3d air controlled arrows.  I have found a more recent game really makes heavy use of this trope, Fenyx Immortals Rising.  It is also quite a bit like Breath of the Wild.  Anyways, hope you are both doing well!

**Comment by ghost** [comment]
Is Fenyx Immortals Rising as pc game never heard of it will look into it. Things are going well here just fed up with lockdown and the only time I can go out is to work its been extended to march now. Work is surprisingly busy but we are having major issue getting supplies in on time after brexit.

**Comment by KMFDManic** [comment]
@grant2258 Fenyx is a an open world adventure game, kind of has elements of stuff such as Zelda Breath of the Wild, Portal Puzzles to a degree.  My wife and myself have been playing it.  Shes been doing the general overworld elements, and when it gets to the crazy ass platforming, I step in, since that is what I am good at,...Ninja Gaiden Black:)  I did a brief video where I played the game with her.

In one area, I joke about the use of arrows like heavenly sword, being like superman 64.  She had a little trouble with the navigation for that section, so she handed me the controller.  She is doing far better at those challenges now!

https://www.youtube.com/watch?v=K8ylJn9EatI

Otherwise, I may pick up another few PS4 Games I missed out on.  But, Fenyx was worth the money, as we both enjoyed it so far!  It all depends on if you like quick pick me up games, or ones that you can play over a period of time, a little at a time.  We have been playing it like 30 minutes to an hour a day, and still havent beaten it.

**Pull request merged**
