### PR TITLE
Multi32 instant resync when switching monitors

### PR DESCRIPTION
**Pull request by mahoneyt944**

### CODE REVIEW

**Comment by KMFDManic** [comment]
Thanks @mahoneyt944 It is definitely nice being able to test variables between Plus/Xtreme, especially when we might encounter regressions, bugs, etc, and can instantly know what needs done, by comparing the two forks:)

**Comment by mahoneyt944** [comment]
Absolutely. This commit allows for the multi32 speed up to still function properly without having the delay created by overriding `system32_displayenable` directly. So we get the speed up perk without any downsides.

**Comment by KMFDManic** [comment]
@mahoneyt944 Seems to be a little snag with compiling, due to this error:

```src/vidhrdw/segas32.c: At top level:
src/vidhrdw/segas32.c:2065:1: error: duplicate ‘static’
 static INLINE UINT8 compute_color_offsets(int which, int layerbit, int layerflag)
 ^~~~~~
src/vidhrdw/segas32.c:2085:1: error: duplicate ‘static’
 static INLINE UINT16 compute_sprite_blend(UINT8 encoding)
 ^~~~~~
src/vidhrdw/segas32.c:2106:1: error: duplicate ‘static’
 static INLINE UINT16 *get_layer_scanline(int layer, int scanline)
 ^~~~~~
Makefile:582: recipe for target 'src/vidhrdw/segas32.o' failed
make: *** [src/vidhrdw/segas32.o] Error 1
```

**Comment by mahoneyt944** [comment]
This should do it https://github.com/KMFDManic/mame2003-xtreme/pull/71/files

**Pull request merged**
