### PR TITLE
Test speed for Ga2 with protection cpu vs simulation code

### PR DESCRIPTION
**Pull request by mahoneyt944**
@KMFDManic try this with the protection cpu hooked up. If there's a noticable performance hit then just disregard this PR as the simulation code we use now works well enough.

### CODE REVIEW

**Comment by KMFDManic** [comment]
@mahoneyt944 @arcadez2003 Tested with Simulation and CPU with Frameskip Off.  There is roughly 3-4 FPS differential between Sim/CPU, with Sim being the higher FPS.  If either of you need to make any other adjustments to test, be sure to let me know.  It isn't an unreasonable hit.  And, it is definitely not going to really affect most platforms, in any case.  But, these are the results, for now:)  With Frameskip on, and Audio/Video Synched, you get fairly close performance/speed.  

This is interesting, as far as comparing any other sort of sim versus cpu protection scheme hookups.

**Comment by mahoneyt944** [comment]
yeah if I could find any examples where the simulation didn't have the correct behavior I'd be more inclined to use the protection cpu, but the sim works just as well and without a performance loss. Probably the best bet to just use the sim

**Comment by KMFDManic** [comment]
@mahoneyt944 let me know if I should revert this or if youd like me to make any other changes, accordingly.

**Comment by mahoneyt944** [comment]
I'll whip up another PR tonight. We're going to keep both options available, but will probably use the sim to save some performance. It's nice to have the option though.

**Pull request merged**
