### PR TITLE
enable artwork

### PR DESCRIPTION
**Pull request by ghost**
that should be it enabled

artwork should l go in 

yoursystemdir/mame2003-xtreme/artwork

ps start invaders to test it

edit dont pull this i added a toggle button not coded in yet let me know if you want it as an option is always on atm

### CODE REVIEW

**Comment by ghost** [comment]
ok added as a core option for you to test

**Comment by KMFDManic** [comment]
Thanks:) Will test now!

**Comment by KMFDManic** [comment]
@grant2258 Compile error with this message:

src/libretro/libretro.o: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
Makefile:535: recipe for target 'km_mame2003_xtreme_libretro.so' failed
make: *** [km_mame2003_xtreme_libretro.so] Error 1

And, thanks so much for helping get this incorporated fully, as it is one of my favorite things to run with!

**Comment by ghost** [comment]
This usually happens on a build fail do a make clean or delete src/libretro/libretro.o and compile again

**Comment by KMFDManic** [comment]
Let me try, thanks:)

**Comment by KMFDManic** [comment]
@grant2258 doh, This is the first time ever I had this error, out of thousands of compiles, hehe.  It compiled fine, now gonna test!

**Pull request merged**
