### PR TITLE
add more frameskip options

### PR DESCRIPTION
**Pull request by ghost**
Let me know how you get on. I would say above 8 isnt useful unless it was been used in auto check capacity though let me know how you get on!

### CODE REVIEW

**Comment by KMFDManic** [comment]
@grant2258 Testing soon, once it compiles:)  Let's hope this one does the trick!

**Comment by ghost** [comment]
since it manual you have to get the higher numbers. Ill see if i can work out some kind of hybrid at some point but manual was always bad I did test the older code It didnt work properly either test it yourself some frameskips numbers done nothing. I might implement something (auto for manual) no promises though it might not even work out.

**Comment by KMFDManic** [comment]
@grant2258 Everything is working, as it should, now:)  Definitely getting the appropriate FPS I expect to get, as I change the numbers.  In fact, it is working better than the way it used to:)  Thanks so much!  That really only leaves one other thing I would like to add, and that might benefit you, as well.  But, it isn't a huge huge deal for the moment, unless you feel it would benefit you, as well.  The bootstrap automation that mahoneyt944 added, so we can have auto nvrams generate for Cruis'n USA, Revolution X, etc.  I need to check the link on those specific overall bootstrap implementation, again.  But, that would certainly be nice, and not sure if you would care for that to be in your barcade, too?  But, man, thanks for looking into this, frameskip is now good, period!

**Comment by ghost** [comment]
I can certainly add it if its needed. I speak to mahoneyt944 now and then and he is a nice guy and a decent coder. I can certainly bring bootstraps to your core it if doesnt have them. Not sure if you have that support at all would need to check.

**Comment by KMFDManic** [comment]
@grant2258 Unfortunately, no, not currently present in Xtreme.  I will just ping him, here, to make things easy!

@mahoneyt944 I would definitely be interested in getting the bootstrap setup into the MAME 2003 Xtreme Core.  Could you relink which commits are useful for doing that, if you don't mind!  

By the way, both of you, with the adjusted, yet not really quite enough stable for Plus, as of yet, frameskip changes, Off Road Challenge is a hell of a lot more playable for me!!!  I will get up a video demonstration in near future.  I even have Killer Instinct running better!  Cruis'n USA, too.  

So, at this point, the bootstrap ability is really what would help drive things further!  Plus, I will be able to have the nifty true Food Fight added, as intended!

Will followup, once either or of you respond:)

Thanks, both of you:)

**Comment by ghost** [comment]
implementation wise its easy enough mark implemented it a while back. 

About the frame-skip there is a hard limit for the auto buffer stuff at 30fps max so games like bubble memory's attract will slow down you might want to change this number to 35 or 40 for the classics. The auto is needed because of the way RA runs.

Manual at least works now its wasnt even fit for purpose even before the video changes the auto should give you the best results though as its dynamic. More work could be some on the manual to get some kind of balance but all in i think the audio buffer is the way to go.

**Comment by KMFDManic** [comment]
@grant2258 This isn't the same thing that Mark did.  This is a further implementation of it.  I just need to find the commit again, so you can see what I refer to.  I will look for the commits, and show you them, if @mahoneyt944 doesn't link to them first:)

**Comment by KMFDManic** [comment]
@grant2258 I believe this is where it starts

https://github.com/libretro/mame2003-libretro/pull/456

**Comment by KMFDManic** [comment]
@grant2258 I will toy around with the 35 or 40 you suggested.  Whatever helps the tough games run best for us:)

Mark did the initial implementation for bootstrapping.  Mahoney did some impressive adding to it for games that normally need calibration to run, such as ones I suggested to look into, like cruisn usa, terminator 2, revolution x, etc.  Revolution X is way nicer with loud sound and calibrated controls:)

Depending on how this works out, I may do another build for more amplitude, as far as execution with legacy and new stuff.

**Comment by mahoneyt944** [comment]
Edit: I see grant created a PR for doing most of the big stuff.

I've have so many bootstrap commits I wouldn't even know where to point you first. But for the general implementation you'll need to:

1. upgrade bootstrap.c and bootstrap.h to the current one in plus. Copy and paste.

2. Any driver that uses a bootstrap needs to have these includes in their header:
#include "bootstrap.h"
#include "inptport.h"

3. Any game using a bootstrap will have a "GAMEC" tag and list the "ctrl" (NULL for you) and bootstrap it uses. Example:

GAMEC( 1994, revx,   0,         midxunit, revx, revx, ROT0, "Midway",   "Revolution X (Rev. 1.0 6-16-94)", &revx_ctrl, &revx_bootstrap )

Games that are imperfect get this tag instead "GAMECX" and will include the imperfect tags as well.

4. There were a few games (2 I think) that had the bootstrap directly in the driver. Both are in the commit you linked above..... We updated the code to use to normal routing and added these bootstraps with all the others. This may not be required in your core if it was never implemented before.

I would update each game one by one and test. I've added a lot. Revx also had a handler fixed up to initiate the audio level on boot. You'll need that too. I think it's found in the machine driver.

**Comment by KMFDManic** [comment]
@mahoneyt944 Yep, @grant2258 and @arcadez2003 are always great with coming to the mod rescue:)  In any case, the frameskipping currently in Xtreme is exactly what I opened an issue about in the Plus fork.  I would suggest trying out my (well, at this point, our) build, if you wanna see it in action.  As grant2258 and myself have noticed, since Plus/Xtreme underwent the "video" update, the frameskipping for Plus/Xtreme was also broken in the process.  What I mean by broken is that certain values cause "frozen onscreen" graphics.  So, you generally can only use 1-2, and then 5, in many cases.  The frameskipping is also quite jittery, which is WHY with the pull request for RetroArch I referred to, which changed up audio buffer monitoring, to make it a smoother experience.  I tested this, and even in this Xtreme Implementation, FrameSkipping is far more nuanced, and not jittery like before.  I ran Off Road Challenge with it, and the results were so nuanced, you had to really try different values to see the difference.  I will do a video demonstration.

I know issues may occur with this being added to Plus.  But, I can test anything if you also want it there, Like grant said, it may require a little more rework, as well.  

But, thanks all of you for really helping push MAME into 2021 and beyond, with some greatness.

I may do an additional fork and get changes from Xtreme into it, so I have Xtreme which is stable for Mini Users, and Amped (which are Cores that aren't stable) for those who wanna push just a bit further.  I messed with audio buffering/frameskipping, much like here with the Xtreme implementation, and such with Nintendo 64, and was able to actually get Vigilante 8 working faster for N64.  This is a game that typically runs slow as molasses on many platforms.  

At around 10:41 for Vigilante 8.  Notice it isn't extremely jittery as typical frameskipping would have.  This can parlay into quite a few Cores, which is what I am going for, for lower spec!  Earlier in the video, I showcase before and after results, with how it usually runs, then how it runs in my implementation.  Excitebike 64 was a big one, as I had to add some override stuff so I could call upon .ini settings for that to properly display without graphical glitches, too.  Needed good graphics, performance, speed.  I would love to get Mesen working like this, someday!

https://www.youtube.com/watch?v=383-Z3Nsyds&t=685s

Chat again, soon:)

Thanks:)

And, lastly, the way some of this works, reducing latency, stability, is kind of like when you have a bike tire spin so fast, it seems to be going backwards.  The change ups and way frameskipping works, it should be choppy.  But, instead, it has that "smooth appearance" like with a backwards tire.  When I was doing code breaker stuff with Dreamcast, years ago, on stuff like Phantasy Star Online, you would think...layman's terms, you could find the value of 32, 767 as the most positive number there could be, and to hurt a fellow player, you'd utilize a health spell!  But, you'd add JUST enough health to that spell, so that it gets to 32, 767, so it would Player Kill them (Of course, I NEVER did this stuff.  But, unfortunately, this malicious coding, not meant to ever be Released at all! was leaked out to the public but a douche canoe who wanted attention at the time), as that would be "negative" value after 32, 767,  I've always thought in terms like that as far as moving forward enough to make things "reset" to negative values, and it has worked for emulation, greatly!  Overclocking too much would definitely hurt performance, too.

**Comment by KMFDManic** [comment]
@grant2258 @mahoneyt944 @arcadez2003 @jdgleaver This is a demonstration of the improved, more nuanced FrameSkipping.  It makes a tremendous difference in games, such as S.T.U.N Runner!

https://www.youtube.com/watch?v=bJl8fhm5cJg

**Comment by ghost** [comment]
Looks like the old style frameskip is working well. How are these games looking on the new auto modes you need 1.9.0 for?

**Comment by KMFDManic** [comment]
@grant2258 frameskipping is far better than it has been in the past.  And, new modes are excellent and will get a near future showcase, as well.  Maybe, one day, even killer instinct may be more playable.  I'll do Karnov video next for ya!

**Comment by ghost** [comment]
nice one so can we call mission frame skip ok for now!.

**Pull request merged**
