### PR TITLE
tidy fps code up now its been tested

### PR DESCRIPTION
**Pull request by ghost**
Just code cleanups no functionality changes. The only thing I did change was new auto  buffer to all 20fps minimum think that will help with classics to be honest.

### CODE REVIEW

**Comment by KMFDManic** [comment]
@grant2258 thanks, as always:)  I will get up a nifty fun Karnov video in the next day or so:)

**Comment by ghost** [comment]
no problems at all my good man. Take some time off and enjoy the festive season!

**Comment by ghost** [comment]
I dont know if ill bee on over the festive period if im not all the best to you and yours!

**Comment by KMFDManic** [comment]
@grant2258 I'll be working. But, I still have a fun Karnov video to do.  I'll let you know once posted.

**Comment by KMFDManic** [comment]
@grant2258 Here ya go, enjoy:)

https://www.youtube.com/watch?v=FWn7DLnO7Ck

**Comment by ghost** [comment]
haha nice one down with karnov! have a goof one over the festive season!

**Pull request closed without merging**
