### PR TITLE
autoframeskip

### PR DESCRIPTION
**Pull request by ghost**
Seen your issue page is untested should work fine though. Is initialized in retro_init remove it from there if you add core options. Right now its set statically to autoframeskip so you can test it. Keep in mind you will need to update RA.

### CODE REVIEW

**Comment by ghost** [comment]
@KMFDManic seen problems testing this should have not assumed anything without testing. I can add the other modes if testing goes well/ From looking at running on a i7 buffer occupancy runs at 48ish in some things so i would suggest something like 50 or 60 if your testing

**Comment by KMFDManic** [comment]
Hey @grant2258 Been a hell of a busy week!  How have things been with you?  And, thanks so much for your input on this.  I am gonna be touching this Core up for a 1-1-21 Release!

I may try to get in some of The Stand Reboot, later today!  In any case, thank you, mate!  Wish we had a better way to chat more easily.  Any chance you could be in Discord, just so chatting is easier, on the fly?  I will test this stuff later today!  You rock!

Be sure to let me know last movie you watched!

**Comment by ghost** [comment]
Dont even remember my password for it if there is any issues needing done will pop on will drop my email on there too. That probably easiest for me all in. But will pop on if there something needing ironed out. I tend to stay away discord and such. Not really been watching much of anything lately with lockdowns im fed up with tv. Its more playing the guitar, playing a game, read a book anything to keep a bored mind active during a pandemic.

**Comment by KMFDManic** [comment]
@grant2258 Guitar to music, like playing some Ozzy Crazy Train, that sort of thing?  And, any other additions to this autoframeskip that need or should be added, or this may be good for now?  You mentioned other modes?

**Comment by ghost** [comment]
> 
> 
> @grant2258 Guitar to music, like playing some Ozzy Crazy Train, that sort of thing? And, any other additions to this autoframeskip that need or should be added, or this may be good for now? You mentioned other modes?

Crazy train is on the playlist lol. I just pretend randy rhodes doent do that magic and just skip the fiddly bits I cant do is a bloody hard song to play properly well beyond my abilities atm.  Right now its only auto the example you posted had 3 settings I think auto should really be fin though if it isint the other setting can be added.

**Comment by KMFDManic** [comment]
@grant2258 Crazy Train I can do drums to, I am not as good on guitar.  Usually drums, keyboards, are more my instruments.  What level of songs you usually play?

**Comment by ghost** [comment]
Originally I learned playing along to metallica seek and destroy and judas priest breaking the law because a friend said there fairly simple songs just played really fast. I found maiden for too fast as a beginner was just impossible.

So I learnt them by memory then worked on my coordination the intros get you the muscle memory well did for me. Now I just load rocksmith up have all the dlc just do and hour or two or random songs or a favorites list there is loads cdlc for it as well so you can get pretty much anything you like.  I cant test the feature because my pc aint sowing down and retropie is still at 1.8.8. If there is any issues ill compile RA for the pie and check it out for what it does it should be fine. I would use elevator action 2 as a test but anything slowing down will be fine really

**Comment by ghost** [comment]
If you get the time try compile my port it has the aggressive and max options added. See if you need them above the auto one you have if so ill port them over for you dont want to add them if they dont make a difference for you just let me know. 

https://github.com/grant2258/blaster-barcade

**Comment by KMFDManic** [comment]
@grant2258 So far, so good.  The only issue will be those who use OLDER RetroArchs won't be able to reap the benefits.  You think there is any way to be able to pull off both Legacy FrameSkip in addition to the dependency driven NEW RetroArch one?  And, yes, I would like the additional options, such as aggressive, and max.  It would be quite useful to be able to have variable control, especially with games such as Cruisn USA/Killer Instinct.  Let me know what you think!  Also, if you do want me to port over your Build, I can do that for the Mini Classics.  Just need to know the stand out points that would be significant to showcase.  For right now, let me know what you think on having dual Legacy/NEW FrameSkip ability, if feasible, or not:)

And, guitar wise, you definitely did the right path.  Sometimes it is nice to try stuff like Green Grass and High Tides, too, see how far you can make it before you start tripping over your own fingers!

**Comment by ghost** [comment]
you branch would require rework, My branch right now only show the  frameskip opton if RA supports it. It  certainly possible. Well my branch is far from complete but is fully functional. I guess the biggest difference inputs are better there is no analog/digital mode analog pedals are mapped and working as well. 

Of course if you  only have digital controls they are mapped to analog as well so use the dpad. Digital games are mapped to the dpad only. Pedals and rotary are automapped.

Ive done some work on the samples so ost sound better and samples. Brought back in the osd and game info menus plus removed.

To avoid confusion ive removed the retroarch remapping functions. The tab menu menu should be used. Ive introduced auto mapping abilities so far its just a few test games.

https://github.com/grant2258/blaster-barcade/blob/d2cf4de10e7f1308d9ea030088ff2c32dfadeb53/src/mame20tike i03/input.c#L563-L582

sf2 ddragon pow and renegade this can also be condition checked to the controller type you select. You can test and fork/rename it if you  like it. This is just a custom build for personal use but if you fork we can adapt it how you want things to suit. Ive changed quiet a bit inputs where completely re-written as the where implemented quite badly

**Comment by KMFDManic** [comment]
For now, I really wouldn't want to change inputs or remaps for my Build, mainly just focus on FrameSkip, Legacy/NEW.  If need be, can enforce NEW, and maintain legacy build for those on older RetroArchs.  In that case, then we could just add the NEW options to the current branch I am on, and that should work out fine.  Auto, then the other options.  This should hopefully help Cruisn/Killer.

**Comment by KMFDManic** [comment]
@grant2258 For now, I really wouldn't want to change inputs or remaps for my Build, mainly just focus on FrameSkip, Legacy/NEW.  If need be, can enforce NEW, and maintain legacy build for those on older RetroArchs.  In that case, then we could just add the NEW options to the current branch I am on, and that should work out fine.  Auto, then the other options.  This should hopefully help Cruisn/Killer.

As far as your build, (remaps, etc) if it works for us, and you don't mind, I have no problem Releasing it and showcasing it for others to enjoy, as well!  More MAME, the better:)

**Comment by ghost** [comment]
Well the rest of the stuff was about my build. All i need you to do on my build  is test if the max and aggressive give you any actual improvement over auto

**Comment by KMFDManic** [comment]
@grant2258 Yeah, that is why I revised my statement, so you knew I was referring to yours, and also that I didn't want to change anything input wise on mine, especially with how nice it currently works.  I will test and let you know.  Moving forward, NEW AutoFrameskip/Aggressive/Max, should really do the trick:)  Let you know in a few!

**Comment by ghost** [comment]
sounds like a plan. I like my build how i want it a well have no trouble tweeking it for you however you like. I completely understand you on that one. I dont have such a great relationship with libretro so keep that in mind when making your decision. I really dont feel like dealing with them bombing me annoyances again and then posting about shit where i cant post back. I dont give a crap what anyone says about me to be honest but if I cant respond to it it just harassment one sided.

**Comment by KMFDManic** [comment]
@grant2258 Creative Freedom of Expression is why I even had drama in our Scene.  It is what it is.  Main thing is, enjoying things as we want, and others being able to enjoy it, too.  As of right now, your build tests out nicely, and your choice of commits is quite excellent and to the point as far as what you are trying to achieve as an end goal.  With that being said, the aggressive and other options will be quite suitable to add to my build.  For those using Old RetroArch, I will just maintain THAT build for them, and anyone on NEW RetroArch can enjoy the NEW FrameSkip nature!  So, if you think we can get the other options in, perfect, and it will be great for RetroArch 190 and on:)  Thanks, mate!

**Comment by KMFDManic** [comment]
And, also, @grant2258 The barcade idea is most excellent.  I know quite a few who will enjoy that sort of implementation and rollout.  They are Arcade Cabinet Enthusiasts, too, always trying to go for as realistic as possible.  That will be a good way to promote your personalized build, for sure:)

**Comment by ghost** [comment]
Well to be honest its just for me I work at my own pace I got most of the internal stuff changed and fixed many long term bugs. I still need to put custom mappings in for toobin and mk and such not many at all 90% work as is with mame. 

The good thing is with the input changes is the joypads work out of the box as well rules can be done on device type. I was boxed in with a macro plus that I couldn't do much with so I just re wrote the input to suit the mame, rather than libretro trying to do what it cant and making it confusing for new people and people that know mame works alike.

New automapping is simple when it  finished if its engaged for a game any changes you make in the tab menu will work but wont be saved else it will be messed up if auto mapping is off because the layout was different when you done the mapping. 

Automapping also wont engage if you change the defaults in this game or general and user will be notified. This way you always get what you map they way it should be. Of course you can just leave it off if you know what your doing. It just helps users for general controls for the few games that dont map if you choose too else turn the mapping off and do it yourself. 

Only some 3 player games need this for controllers mk and toobin ect also need some love. But generally decent defaults should solve 90% of the problems. Ill let let you know when this is complete it will let your remap for now. 

It was pretty funky paying super off road with an analog pedal mapped to L2/R2 for digital or LT/RT for analog it will figure it out from what the controller feed back.  

The reason for not mapping digital to the analog stick is a personal one it can be mapped to both easily enough.   I easy explain it this way  lightgun games suck with analog joysticks so move to that dpad and you can still do your lightgun games with a joypad or them dial games that suck balls on a analog stick just use your dpad or arcade digital joystick for theses ones. It enforces a consistency that the digital pad isint an analog control that all. 

Ill have a think about the best way to do this. RA does have new options menus but that the same trap as the new frameskip options if you version of ra is too old it wont work. I could certainly add both. (Auto_likely) (Auto_agressive)  (Auto max), (manual_1),  (manual_2), (manual_3),(manual_3) and just give a notification to the user if auto doesnt work.

**Comment by ghost** [comment]
Another useless bit of information this https://github.com/medusalix/xow motivated me to add the digital controls only for dpad as well the xbox one dpad pad is great for 8 ways sticks i know some are awful though.

**Comment by ghost** [comment]
The old frameskip is really broken. I added code to use old and new.  Manual options specially 3 makes the video update stop all together.

Ill look at fixing this it shouldnt be that bad. To be honest i never used frameskip because it was so bad in retroarch and the frameskip counter shouldnt be added in osd_skip frame.

I dont know if this worked properly before the video update regardless will try get it fixed!

**Comment by KMFDManic** [comment]
@grant2258 yes, it did work before we did video update to both plus/Xtreme.  I thought I had brought it up before.  In any case, case by case scenario, most games work at 1, 2, some at 3, etc.  Its been fine for what I needed it to do.  Looking very forward to whatever you feel is most appropriate.  And, great work on your barcade core, by the way!

**Comment by ghost** [comment]
Yea the even the ones that work are overly jittery sorry if i missed you bringing this up before. I had no idea it was in this state no ones really picked it in issues that ive seen anyway. Its amazing what you find when you use options you dont usually use!

**Comment by ghost** [comment]
Ok ive updated my core branch give it a wee test run and let me know if this ok for you when you have time and ill port it over for you. I d like to get it done in one commit for you. Assuming there isint any issue should get it done for you tonight. I still need to add notifications about the auto failing is easy enough if you want that. That frameskip was absolutely shocking

**Comment by KMFDManic** [comment]
Things are looking amazing on your branch:)  This should work out great to cover old and new retroarch, exactly what I was hoping for!  Thanks, as always, for continuing to help make MAME so awesome.  Both you and Arcadez2003 rock!  Looking forward to the execution of this on Xtreme, too.

**Comment by ghost** [comment]
contributors with a decent ethic like yourself its never and issue helping!

**Comment by KMFDManic** [comment]
For some of us, gaming isnt just a fad.  It's a lifestyle hehe.  I've been interested in gaming since the Atari 2600 days.  Retro inspired games still get my attention most! What was the last game you played with barcade? @grant2258

**Comment by ghost** [comment]
Think it was pinball action or tiger road to be honest. My mission is to finish karnov one day. I dont use the pi much usually do shed load of updates then spend a few days testing. Else i wouldn't get anything done haha! I probably played more before Amidar is about where my memory sits with the first games i like in the arcades. I remember being sick off school I snuck in in the local cafe to play black tiger  haha!

Is bed time here my good man your pull request is in let me know if you have any issues. Hopefully the manual worked like it did before! All the best for xmas!

**Comment by KMFDManic** [comment]
@grant2258 when in doubt, play the entire first stage of Bad Dudes, then you should have no trouble beating:)  it is an insane game, for sure.  I made it quite far in the NES Karnov.  Data East has put out some truly excellent games.

I will test the pull request when home from work later today.  Thanks again!

**Comment by KMFDManic** [comment]
**This is in regards to the OTHER pull request, Xtreme Frameskip for Classics**

@grant2258 Ok, in retesting everything (games I KNOW needed frameskip, the frameskip works fine with current RetroArch.  But, on older RetroArchs, no go.  This isn't too big a deal, for now, as I will just post the build that runs with it, as well as this beefed up one that you helped with, that runs admirably, and greatly helps Killer Instinct, Cruis'n USA for NEW RetroArch:)  I am gonna do a Karnov video, too.  I think you may like it!  ONLY worry about Legacy FrameSkip if you know it is doable.  Where we are, for now, it is workable!  

I would suggest you attempt listening to Outlaws - Green Grass and High Tides, and try to see if you can play some guitar to that!  It is a fun one!

**Comment by ghost** [comment]
Just to clarify you saying manual frameskip isint working on the new build in the other pull request?

**Comment by KMFDManic** [comment]
@grant2258 Odd, I responded to this message on my phone, and am seeing it did not go through!  In any case, yes, I am referring to manual frame skip.  I had to retest, to be sure.  But, behavior is clearly not indicative of it properly detecting and working, even after a restart.  So, it would seem it mainly works with NEW RetroArch.  If you think it can be fixed up, let me know, and I will gladly retest.  It certainly has practical applications, which I can showcase, when this is all said and done.

And, with your interest in Karnov, it gave me a fun idea.  I will do a "rage humor" video where I try to beat Karnov, and then do some silly stuff!

Again, thanks for your help on this, as once it works and is implemented, it should truly help with some stubborn games!
 
I can test as many changes as need changed, til we get it right.  Or, if it is a burden, let it be moving forward for NEW RetroArch only, and Legacy Support the OLD RetroArch with a specific scenario setup build.  Talk soon!

**Pull request merged**
