### PR TITLE
More cleanup

### PR DESCRIPTION
**Pull request by mahoneyt944**

### CODE REVIEW

**Comment by KMFDManic** [comment]
Thanks, @mahoneyt944 As of now, everything appears to be nicely functional. I may have to do a speed boost of sorts for the multi32 games as they are somewhat slower now than the far less accurate, previous incarnation.  I did a similar speed boost to help virtua racing and xmen 6 player (recent commit), both of which were too slow on my platforms. 

Ill have to get used to the controls for Title Fight, too, for a good showcase.

Exceptional work. Thanks again!

**Comment by mahoneyt944** [comment]
mix_all_layers() takes a hit on performance. Displaying only one screen should help performance and any other tricks you want to try.

**Comment by mahoneyt944** [comment]
Here's the control panel overlay describing the different blocks and attacks

significantly

**Comment by KMFDManic** [comment]
@mahoneyt944 thanks:)

**Pull request merged**
