### PR TITLE
add xtreme frameskip fixes for the classics community

### PR DESCRIPTION
**Pull request by ghost**
Hopefully thats  us, Ive added a notifiction if Ra doesnt support the audio buffer.

### CODE REVIEW

**Comment by KMFDManic** [comment]
Thanks:)

**Comment by ghost** [comment]
Im just trying to figure out whats going on here its a big confusing. Just a couple of questions to clear up.

1) is manual frame skip (0 - 5) not working for you I tested it with elevator action returns had to set it to 5 and the game was fine on the pie on my core anyway

2) auto modes wont work at all an anything lower than 1.9.0

**Comment by KMFDManic** [comment]
@grant2258 you tested my core, as well as barcade?  I can retest again, just to be sure.  If it works for you, then it might be just be on my end.  Thanks!  I will retest barcade, as well as my core, so we can see for sure.  Which retroarch version you using anyways?

**Comment by ghost** [comment]
Well i compiled your core for windows and put it on frameskip5 and my fps dropped so is functioning as such ill compile your core on my pi and let you know. Might need to add more aggressive options as well 0 11 instead of 0 - 5

**Comment by KMFDManic** [comment]
@grant2258 I really appreciate the Xtra mile:) And, yeah, Elevator Action Returns is a perfect test example for frameskip!

**Comment by ghost** [comment]
Well 5 is only good for around above 35 fps will need to add the higher numbers. Lemme grab a coffee should be done quick :)

**Comment by KMFDManic** [comment]
@grant2258 thanks, will test when you're done:)

**Pull request merged**
