### PR TITLE
Resolution change when zooming

### PR DESCRIPTION
**Pull request by mahoneyt944**
This should fix the background issue in harddunk without the kludge.

### CODE REVIEW

**Comment by KMFDManic** [comment]
@mahoneyt944 Did my observation about the zooming in and out happening during the noticeable slowdowns help with this path?  Looks great, by the way, will test!

**Comment by mahoneyt944** [comment]
The zooming in and out in harddunk is actually done in sprites, the zooming here is explicitly for backgrounds so they aren't the same. My theory is that the background should increase resolution only when zooming. But this is an educated guess based on the misbehavior of locking the resolution high. Seems to work with everything I tested.

**Comment by KMFDManic** [comment]
@mahoneyt944 Testing looking good, thus far.  Slipstream and Super Cross also seem to benefit, as I get slightly higher FPS all around.  Will do more testing and see if I need to make any clock adjustments, and stay tune for anything else you might think of.  Thanks again!  Great theory and working things out Plus/Xtreme Wise:)

**Comment by mahoneyt944** [comment]
If this resolution change makes a difference, it should benefit a lot of the games as it's applied to all games in the driver. Glad it's showing promise.

**Pull request merged**
